# Generated by Django 5.0.8 on 2024-09-05 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="response_type",
        ),
        migrations.AddField(
            model_name="message",
            name="response",
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
