# Generated by Django 4.2.11 on 2024-08-09 04:50

from django.db import migrations


class Migration(migrations.Migration):
    """ """

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="conversation",
            table="conversations",
        ),
    ]
