# Generated by Django 4.2.11 on 2024-08-09 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_alter_conversation_table"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conversation",
            name="end_time",
        ),
        migrations.RemoveField(
            model_name="conversation",
            name="start_time",
        ),
    ]
