# Generated by Django 5.0.8 on 2024-09-05 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_remove_message_response_type_message_response"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="response",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
