# Generated by Django 4.2.11 on 2024-08-11 16:59

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    """ """

    dependencies = [
        ("chat", "0005_message_created_at_message_updated_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FAQS",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("question", models.TextField()),
                ("answer", models.TextField()),
            ],
            options={
                "db_table": "frequently_asked_questions",
            },
        ),
    ]
